swagger: "2.0"
info:
  title: API CRM APP 2025
  version: 1.0.0

securityDefinitions:
  Token:
    type: apiKey
    name: Authorization
    in: header
    description: Nhập token trực tiếp (ví dụ -> 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...')

security:
  - Token: []  # Áp dụng Token cho tất cả endpoint

# paths:
#   $ref: './paths/hoa-don-xuat-kho.yaml'  # Tham chiếu file endpoint
#   # Thêm các $ref khác nếu bạn có thêm endpoint